homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 566
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

  customize: !include customize.yaml
 
zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 150
  icon: mdi:home-variant

zone 2:
  name: Arbeit
  latitude: !secret arbeit_lat
  longitude: !secret arbeit_long
  radius: 100
  icon: mdi:worker
  
zone 3:
  name: Moos
  latitude: !secret moos_lat
  longitude: !secret moos_long
  radius: 100
  icon: mdi:face

zone 4:
  name: Billa
  latitude: !secret billa_lat
  longitude: !secret billa_long
  radius: 100
  icon: mdi:weight

# Enables the frontend
frontend:
  
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: 192.168.0.58
  trusted_networks:
    - 192.168.0.0/24
    - 127.0.0.1

# Checks for available updates
updater:

recorder:
  db_url: postgres://@/hass
  purge_days: 14
# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - sun
      - group.speedtest
      - device_tracker
  exclude:
    entities:
    - media_player.unnamed_device
    - sensor.yr_symbol
    - sensor.pws_station_id

# View all events in a logbook
logbook:

logger:
#Possible Values
#critical
#fatal
#error
#warning
#warn
#info
#debug
#notset

  default: error
#  logs:
#    homeassistant.components.rest_command: debug

# Track the sun
sun:

# Weather Prediction
sensor: !include sensor.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret username_mqtt
  password: !secret password_mqtt

media_player: !include mediaplayer.yaml

input_slider: !include slider.yaml

device_tracker: !include device_tracker.yaml

binary_sensor: !include binary_sensor.yaml

switch: !include switch.yaml

shell_command: !include shell_command.yaml

script: !include script.yaml

automation: !include automation.yaml

group: !include group.yaml

notify: !include notify.yaml

light: !include light.yaml

input_select: !include input_select.yaml

emulated_hue: !include emulated_hue.yaml

input_boolean: !include input_boolean.yaml

alexa: !include alexa.yaml

rest_command: !include rest_command.yaml

neato: !include neato.yaml

panel_iframe: !include iframe.yaml