- platform: yr
 
#- platform: speedtest
#  minute:
#    - 30
#  monitored_conditions:
#      - ping
#      - download
#      - upload

- platform: wunderground
  api_key: !secret wundergroud_api_key
  pws_id: IAIGEN4
  lang: DL
  monitored_conditions:
    - weather
    - temp_c
    - station_id
    - feelslike_c
    - wind_kph
    - pressure_mb
    - wind_dir
    - relative_humidity
    - visibility_km

- platform: mqtt
  state_topic: 'sensor/wohnzimmer/dht22'
  name: "Temperatur Wohnzimmer"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'
    
- platform: mqtt
  state_topic: 'sensor/wohnzimmer/dht22'
  name: "Luftfeuchte Wohnzimmer"
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'sensor/esszimmer/dht22'
  name: "Temperatur Esszimmer"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'
    
- platform: mqtt
  state_topic: 'sensor/esszimmer/dht22'
  name: "Luftfeuchte Esszimmer"
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
  