- alias: alexa_fernsehen
  trigger:
    platform: state
    entity_id: input_boolean.fernsehen
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Fernsehen"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.fernsehen

- alias: alexa_ps4
  trigger:
    platform: state
    entity_id: input_boolean.ps4
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "PS4"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.PS4

- alias: alexa_wii
  trigger:
    platform: state
    entity_id: input_boolean.wii
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Wii spielen"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.wii

- alias: alexa_snes
  trigger:
    platform: state
    entity_id: input_boolean.nintendo
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "SNES"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.nintendo

- alias: alexa_bluetooth
  trigger:
    platform: state
    entity_id: input_boolean.bluetooth
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Musik hören"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bluetooth

- alias: alexa_kodi
  trigger:
    platform: state
    entity_id: input_boolean.kodi
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Kodi"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.kodi

- alias: alexa_heimkino_aus
  trigger:
    platform: state
    entity_id: input_boolean.heimkino
    to: "off"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Aus"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.heimkino

- alias: alexa_smarttv
  trigger:
    platform: state
    entity_id: input_boolean.smarttv
    to: "on"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fernbedinung
        option: "Smart TV"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.smarttv